"""add category table and category_id to questions

Revision ID: 583ecedcecb2
Revises: f550f7a04e4a
Create Date: 2026-07-05 11:55:04.115686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583ecedcecb2'
down_revision = 'f550f7a04e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_questions_categories_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_category_id_categories'), 'categories', ['category_id'], ['id'])
        batch_op.drop_column('categories_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_questions_category_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_questions_categories_id_categories'), 'categories', ['categories_id'], ['id'])
        batch_op.drop_column('category_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###