"""migration

Revision ID: f550f7a04e4a
Revises: 10286bc2f66c
Create Date: 2026-07-02 12:34:00.611720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f550f7a04e4a'
down_revision = '10286bc2f66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['categories_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categories_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
